### ISSUE TITLE
QR Code Scanner not working on lenovo tablet

### ISSUE THREAD

**Issue by jacksos101** [ssm-deepcove/discover_deep_cove#10]
Something to do with our use of the code, as Ken made a demo app that works correctly.

**Comment by MitchellQ** [comment]
This bug seems to occur exclusively on the Lenovo tablet supplied by the trust,
I have done alot of testing but I can't track down the source of the bug, I have tested
- creating my own basic version of the library and that works fine
- ken had added kotlin support using the wizard in android studio however I created the same app in vs code without using kotlin and had no issues - we should include kotlin anyway as that is recommended in the library dcos
- it can't be the qr identification code as the error takes place before the qr code is scanned 
- it isn't a hardware issue as we have got it working on the tablet.

if you want to double check my findings and have suggestions of what other areas when can check feel free to test these

**Comment by jacksos101** [comment]
Must be the way that the scan() function is being called.

**Comment by MitchellQ** [comment]
I using the same method it is the same library after all
